### ISSUE TITLE
Not working with Hearts of Iron 4

### ISSUE THREAD

**Issue by Tarballwalf** [20PercentRendered/creamlinux#13]
game owned on steam.
tried both bin and building from source.
tried making my own creamapi.ini from scratch.

my bets are on `libCreamlinux.so`, launch script seems to be fine

although, I did manage to get it working, but by downloading the DLC's from another game.

also, would the `unlockall = true` variable work?

**Comment by Tarballwalf** [comment]
seems like hoi4 is so poorly coded, I can just put the DLC's there, and it just works
still, creamlinux does not work at all

tested with
* Hearts of Iron 4
* Cities: Skylines

**Comment by 20PercentRendered** [comment]
Creamlinux simply fakes the steam apis necessary for the game to check the dlc's ownership. Without the actual DLC files (from another source) it won't do anything.

**Comment by Tarballwalf** [comment]
consider adding that to the `readme.md`. documentations are very vague.

**Comment by 20PercentRendered** [comment]
I will add it soon
