### ISSUE TITLE
No lauch options shown.

### ISSUE THREAD

**Issue by ded-moon** [20PercentRendered/creamlinux#14]
![Screenshot_20221024_132854](https://user-images.githubusercontent.com/70951560/197506299-de7e38bf-1bfa-4eb6-9af2-497bca26e66b.png)

Potentially missing package on Manjaro.

**Comment by ded-moon** [comment]
Launching with steam option seems to cause that issue. Running directly from terminal works.

**Comment by 20PercentRendered** [comment]
Steam bundles an old version of gtk, so the dialog looks strange. Have you tried to scroll that area?

**Comment by 20PercentRendered** [comment]
I have released a new version of creamlinux. Try using the new launch args `CREAM_SIMPLE=1 sh ./cream.sh %command%`, and tell me if it works.

**Comment by Tarballwalf** [comment]
I seem to be getting the same thing now. Running with `CREAM_SIMPLE=1` opens up the Paradox Launcher, loads for a bit, and then it closes immediately. Removing that results in no options shown.

**Comment by 20PercentRendered** [comment]
That is good and means creamlinux is loading successfully. The paradox launcher does crash with creamlinux, so you will need to use the "skip launcher" launch option.

**Comment by 20PercentRendered** [comment]
Please retest with the new 2.0 creamlinux version.

**Comment by Tarballwalf** [comment]
Works amazingly. Thank you so much.
Would be amazing if the automatic DLC content fetching would work too, like on Windows.

**Comment by 20PercentRendered** [comment]
It could be pretty cool, but it is unfortunately outside the scope of this project.

**Comment by 20PercentRendered** [comment]
Closing as fixed.

**Comment by 20PercentRendered** [comment]
Closing as fixed.
