### ISSUE TITLE
Stellaris broken

### ISSUE THREAD

**Issue by pipoliviero** [20PercentRendered/creamlinux#15]
When I start from steam it says running and then closes immediately without even opening a window or anything.
Starting from terminal with `sh ./cream.sh` just results in `./cream.sh: 13: Syntax error: "(" unexpected`
`sh ./cream.sh %command%` opens a small menu with two buttons. Both buttons seem to do nothing.
`CREAM_SIMPLE=1 sh ./cream.sh` just does nothing
`CREAM_SIMPLE=1 sh ./cream.sh %command%` results in `./cream.sh: 5: %command%: not found`

Sorta new to linux here so not sure what I'm doing wrong. I tried with the release and building it myself and I had the same result.

**Comment by 20PercentRendered** [comment]
You need to put that in Steam's launch arguments for the game.

**Comment by pipoliviero** [comment]
> When I start from steam it says running and then closes immediately without even opening a window or anything.

**Comment by 20PercentRendered** [comment]
As in putting it in the launch arguments does nothing? Could you send me a screenshot of your launch arguments? Also, `cream.sh` is not meant to be ran from the terminal.

**Comment by pipoliviero** [comment]
![image](https://user-images.githubusercontent.com/10493036/199995695-09f8d9a5-d4a6-4d1a-9fb9-aa35196f58de.png)

For whatever reason today it opens the two button menu but both buttons still do nothing.

![image](https://user-images.githubusercontent.com/10493036/199995874-39682d53-944b-4c70-a54c-aa8b09423cf0.png)

**Comment by 20PercentRendered** [comment]
Do you have the latest version of creamlinux? You can just copy the cream.sh over from the new release, I didn't change anything else. It includes the CREAM_SIMPLE support.

**Comment by pipoliviero** [comment]
Yes I downloaded it yesterday for the first time.
Just to get ahead, yes I redownloaded stellaris, and the game works fine without cream.

**Comment by 20PercentRendered** [comment]
Please retest with the new 2.0 creamlinux version.

**Comment by pipoliviero** [comment]
Thanks for the updates. <3

The cream_api.ini is missing:

2115770 = Stellaris: Toxoids Species Pack
1889490 = Stellaris: Overlord
633310 = Stellaris: Anniversary Portraits
554350 = Stellaris: Horizon Signal

It now works perfectly for me.

**Comment by 20PercentRendered** [comment]
You can create a pull request to add those IDs if you wish.
