### ISSUE TITLE
Games currently working

### ISSUE THREAD

**Issue by rednatnas** [20PercentRendered/creamlinux#19]
Hello! I have tested and played for many hours the following games without any problem:

- Stellaris (3.6.0 and the current version 3.7.3)
- Crusader Kings II
- Surviving Mars

I hope this information is useful!

Edit: I checked my files and I was **wrong**, I tought that I was using the last version of creamlinux but I'm not (V1.3) because the zenity gui is still present. I retried with the current version of creamlinux and it doesn't work (Stellaris 3.7.3).
I would like to know why it doesn't. Sorry!

**Comment by clamor-s** [comment]
@rednatnas which version of creamlinux you used?

**Comment by 20PercentRendered** [comment]
Do you have a list of games that don't work as well?

**Comment by rednatnas** [comment]
> Do you have a list of games that don't work as well?

No, it work in all the games I've tried it on, those 3 for now. Thanks for your work btw.

**Comment by rednatnas** [comment]
> 

The last one. You have to edit the cream_api.ini for the new DLC's, maybe you wrote the IDs wrong?

**Comment by clamor-s** [comment]
@rednatnas I have written and get error anyway

**Comment by rednatnas** [comment]
> @rednatnas I have written and get error anyway
I don't think the problem is the CreamApi, try to replace all DLC's, make sure that are the latest version and check the ID's in cream_api.ini with SteamDB. Hope it works for you!

**Comment by clamor-s** [comment]
@rednatnas I have re-downloaded all dlc, and which is interesting, even free dlc (HorSign and AnnivPortraits) brake

**Comment by rednatnas** [comment]
I have edited my comment, I tought It work but I did't realized that I was using an old version. Sorry!

**Comment by clamor-s** [comment]
@rednatnas thank you very much! This means that rolling back to 1.3 will fix stellaris. Awesome!

Interesting is that 1st contact works as is with 2.0
