### ISSUE TITLE
Compile & Usage issue

### ISSUE THREAD

**Issue by clamor-s** [20PercentRendered/creamlinux#2]
- isteamremoteplay.h
- isteamnetworkingmessages.h
- isteamnetworkingsockets.h
- isteamnetworkingutils.h

are requested by `stream_api.h` and are missing

**Comment by 20PercentRendered** [comment]
Will fix by auto-downloading steamworks headers.

**Comment by 20PercentRendered** [comment]
That's strange. Yes, it does work the same as Windows creamapi, so multiplayer will be available. As for game launching, just put the cream.sh line into launch options, just make sure you've got the build output copied over to the game dir.

**Comment by clamor-s** [comment]
I'm getting /usr/bin/ld: unable to get -lsteam_api

**Comment by 20PercentRendered** [comment]
huh, strange. It seems the last commit I pushed did not fully include all files (spdlog, some steam files). Working on it. Sorry it's taking so long.

**Comment by 20PercentRendered** [comment]
@clamor-s Try it now?

**Comment by clamor-s** [comment]
@20PercentRendered no problems. Now I have recursive clone fail
`git@github.com: Permission denied (publickey).` not on which side error occures

**Comment by 20PercentRendered** [comment]
Open Steam in a terminal, so we can get log outputs. Then, copy files from build/lib. Now, set the game's launch options to "./cream.sh %command%". Now, click play. Then pick "Start Game", stellaris should be on that list. If the DLCs don't work ingame, then copy The log output here, as we might need to add a steamworks api version

**Comment by clamor-s** [comment]
I have set game launch option but launcher does not start

**Comment by 20PercentRendered** [comment]
You can start the launcher, but you shouldn't launch the game from there, because it won't load creamlinux in that case. You can manage mods and DLCs just fine from there though.

**Comment by clamor-s** [comment]
Launcher starts and immidiatelly closes.

**Comment by 20PercentRendered** [comment]
This is an issue I just remembered about. I have the fixed code, but it got ignored in the pushing process like the previous code It's due to "./dowser" not being detected and it LD_PRELOADing.

**Comment by clamor-s** [comment]
So script launches it same as game and it fails.

**Comment by 20PercentRendered** [comment]
Good to hear. Will improve this project and documentation. 
Drop merge commit? Like disable it?

**Comment by clamor-s** [comment]
No no. Checkout to my commit and rebase on top your, avoiding merge commit. You may add me as co-dev, I will drop it and then remove be from co-dev.

**Comment by 20PercentRendered** [comment]
Ah ok. I prefer merge commits though. Makes it clearer to see history.

**Comment by clamor-s** [comment]
Ok, as you wish. Please ping me when you would need some mote tests.

**Comment by 20PercentRendered** [comment]
Closing as documentation was improved and headers were fixed. Remaining issues are tracked in #4 #6
